
export const ActionTypes = {
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS' ,
    GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL' ,
    PRODUCTS_LOADER: 'PRODUCTS_LOADER',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SELECTED_ITEM: 'SELECTED_ITEM', 
    PRODUCTS_COUNTER_INCREMENT: 'PRODUCTS_COUNTER_INCREMENT',
    PRODUCTS_COUNTER_DECREMENT: 'PRODUCTS_COUNTER_DECREMENT',
    ADD_PRODUCT_TO_ADMIN_PANEL: 'ADD_PRODUCT_TO_ADMIN_PANEL',
    PRODUCT_ACCEPTED: 'PRODUCT_ACCEPTED',
    REMOVE_PRODUCT_FROM_ADMIN_PANEL: 'REMOVE_PRODUCT_FROM_ADMIN_PANEL',
}